CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    note_text TEXT,
    modified TIMESTAMP DEFAULT now() NOT NULL,
    folderId INTEGER REFERENCES folders(id)
);

